baseURL = "https://conradludgate.com/"
languageCode = "en-gb"
title = "Conrad Ludgate"
theme = "noteworthy"
enableRobotsTXT = true
paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.

[author]
    name = "conradludgate"

[taxonomies]
    tag = "tags"
    

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
    unsafe = true

[params]
    math = true
    # Blog description at the top of the homepage. Supports markdown.
    description = "Hi. I write code sometimes"

    twitter = "https://twitter.com/conradludgate"
    linkedin = "https://www.linkedin.com/in/conrad-ludgate-a78090159/"

    # Programming
    github = "https://github.com/conradludgate"

    ackee_analytics_src = "https://api.conradludgate.com/api.js"
    ackee_server = "https://api.conradludgate.com"
    ackee_domain_id = "97fd72f0-e2a9-44e1-a3fd-1ef2d3611b58"


# Menu links along the sidebar navigation.
[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
	identifier = "tags"
	name = "Tags"
	url = "/tags/"
	weight = 2

# [[menu.main]]
# 	name = "Archives"
# 	identifier = "archives"
# 	url = "/archives/"
# 	weight = 3